language: go
sudo: required
dist: trusty
go:
- '1.10'
os:
- linux
install:
- go get github.com/stretchr/testify/assert
- go get firebase.google.com/go


script:
- go test -v -coverprofile=c0.out -covermode=atomic github.com/mchirico/septa/utils github.com/mchirico/septa/utils
- go test -v -coverprofile=c1.out -covermode=atomic github.com/mchirico/septa/utils github.com/mchirico/septa/firebase

before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

# - sudo apt-get update -q

- openssl aes-256-cbc -K $encrypted_032be19076da_key -iv $encrypted_032be19076da_iv
  -in token.json.enc -out token.json -d

after_success:
- cat c0.out c1.out > c.out
- cp c.out coverage.txt
- bash <(curl -s https://codecov.io/bash)
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT






